version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: InventoryManagement.Endpoints/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
    depends_on:
      - rabbitmq
    # Add other production-specific configurations as needed
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"