version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: InventoryManagement.Endpoints/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq-network    
networks:
  rabbitmq-network:
    driver: bridge